# Generated by Django 6.0.1 on 2026-01-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailhandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('recipient_list', models.JSONField()),
                ('sent_at', models.TimeField(auto_now_add=True)),
                ('sent_count', models.IntegerField(default=0)),
            ],
        ),
    ]
